#!/bin/bash
########################################################################
####  Script Name: sm-lib-warning
####  version: 1.2.2
####  Date: July 2 2008

####  Copyright (C) Harald Hope 2005-2008
####  This program is free software; you can redistribute it and/or modify it under 
####  the terms of the GNU General Public License as published by the Free Software
####  Foundation; either version 2 of the License, or (at your option) any later version.

####  This program is distributed in the hope that it will be useful, but WITHOUT 
####  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
####  FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

####  Get the full text of the GPL here:
####  http://www.gnu.org/licenses/old-licenses/gpl-2.0.html

####  Script Author: Harald Hope 
####  This is a library file for smxi and cannot be run independently

####  Script URL: http://techpatterns.com/downloads/distro/sm-lib-warning
####  Script Home page: http://techpatterns.com/forums/about736.html
########################################################################

# get remote server status
get_status()
{
	wget -T$TIME_OUT -t2 -Ncq $TECH_PATTERNS_DISTRO$UPGRADE_DATA$WARNING_STATUS
	
	if [ -f $WARNING_STATUS ]
	then
		STATUS=$( cat $WARNING_STATUS)
		rm -f $WARNING_STATUS
	else
		echo $EBAR
		echo "${E}Failed to download error status data. Please wait to continue with $DU_UPGRADE."
		echo $EBAR
		exit 0
	fi
}

# get warning text if required
get_warning()
{
	if [ "$STATUS" == 'danger' -o "$STATUS" == 'danger-alert' -a "$1" == 'danger' ]
	then
		wget -T$TIME_OUT -t2 -Ncq $TECH_PATTERNS_DISTRO$UPGRADE_DATA$WARNING_BODY
		if [ -f $WARNING_BODY ]
		then
			cat $WARNING_BODY
			rm -f $WARNING_BODY
		else
			echo $EBAR
			echo "${E}Failed to download warning text data. Please wait to continue with $DU_UPGRADE."
			echo $EBAR
		fi
	fi
	if [ "$STATUS" == 'alert' -o "$STATUS" == 'danger-alert' -a "$1" == 'alert' ]
	then
		wget -T$TIME_OUT -t2 -Ncq $TECH_PATTERNS_DISTRO$UPGRADE_DATA$ALERT_BODY
		if [ -f $ALERT_BODY ]
		then
			cat $ALERT_BODY
			rm -f $ALERT_BODY
		else
			echo $EBAR
			echo "${E}Failed to download alert text data. Please wait to continue with $DU_UPGRADE."
			echo $EBAR
		fi
	fi
}

# this isn't properly part of the warning system, but it's still reasonably
# related. This is called in pre du-1, so users can actually remember the config files
get_configs()
{
	wget -T$TIME_OUT -t2 -Ncq $TECH_PATTERNS_DISTRO$UPGRADE_DATA$CONFIGS_BODY
	
	if [ -f "$CONFIGS_BODY" -a -n "$( cat $CONFIGS_BODY )" ]
	then
		echo "${M}Answer ${C}y${M} instead of the standard ${C}n${M} if you are asked to"
		echo "replace the following config files during $DU_UPGRADE:${N}"
		cat $CONFIGS_BODY
		echo
		echo $MLINE
	fi
	if [ -f "$CONFIGS_BODY" ]
	then
		rm -f $CONFIGS_BODY
	fi
}

# issue warning if status = danger etc
upgrade_warning()
{
	local ContinueText='' options='' opt=''
	
	get_status

	if [ "$STATUS" == 'alert'  -o "$STATUS" == 'danger-alert' ]
	then
		echo $EBAR
		echo ${E}"*******     CURRENT ALERTS & FIXES"
		echo $EBAR
		get_warning alert
		echo
		
		ContinueText="${E}Continue with ${C}$DU_UPGRADE${E}. Proceed with caution. Watch for fixes noted above."
	fi
	
	if [ "$STATUS" == 'danger' -o "$STATUS" == 'danger-alert' ]
	then
		echo $WBAR
		echo "${W}*******     IT IS NOT CURRENTLY SAFE TO $( tr [a-z] [A-Z] <<< $DU_UPGRADE )"
		echo ${W}"*******     CURRENT WARNINGS(s)"
		echo $WBAR
		get_warning danger
		echo
		echo $LINE
		echo "${S}Please wait to do the $DU_UPGRADE until you have received word "
		echo "that it is safe, or until the script runs without displaying this warning."
		echo
		echo "Check the forums and news page of sidux.com for further information."
		
		ContinueText="${W}Continue with ${C}$DU_UPGRADE${W}. Proceed at your own risk!!!"
	fi
	
	if [ "$STATUS" == 'proceed' ]
	then
		echo $MBAR
		echo "${M}There are currently no known major issues with ${C}$DU_UPGRADE${S}"

		ContinueText="${S}Continue with ${C}$DU_UPGRADE${S}."
	fi
	
	echo $LINE
	echo "${C}1${S} - $ContinueText"
	echo "${C}2${S} - Continue without doing the ${C}$DU_UPGRADE${S}."
	echo "    This will let you do graphics install and various other smaller functions."
	echo
	echo "${C}3${S} - Quit the script now."
	echo $LINE
	echo $SLE
	echo $LINE
	
	options="continue continue-no-$DU_UPGRADE quit"
	select opt in $options
	do
		case $opt in
			continue|c)
				# start xorg install, update, dist-upgrade, xorg component install
				install_dist_upgrade first
				;;
			continue-no-dist-upgrade|continue-no-upgrade)
				echo "${S}Skipping ${C}$DU_UPGRADE${S} for now. Continuing with script.${N}"
				;;
			quit|q)
				print_quit
				exit 0
				;;
			*)
				print_error opt
				upgrade_warning repeat
				;;
		esac
		break
	done
}
#upgrade_warning

###**EOF**###